@LoggingWithCorrelationIdDemo_HostAddress = http://localhost:5284

GET {{LoggingWithCorrelationIdDemo_HostAddress}}/Failing/testRetry/
Accept: application/json
###


GET {{LoggingWithCorrelationIdDemo_HostAddress}}/Failing/testException/
Accept: application/json
###


GET {{LoggingWithCorrelationIdDemo_HostAddress}}/todo/1/
Accept: application/json
X-Correlation-Id: zebra
###



GET {{LoggingWithCorrelationIdDemo_HostAddress}}/health/live
Accept: application/json
X-Correlation-Id: zebra
###



POST {{LoggingWithCorrelationIdDemo_HostAddress}}/todo/1/
Content-Type: application/json
X-Correlation-Id: zebra

{
  "userId": 1,
  "title": "ssss",
  "completed": false
}
###
